### ISSUE TITLE
SFD2017@Shanghai - Event Planning

### ISSUE THREAD

**Issue by CCharlieLi** [SFD-Shanghai/SFD2017#1]
- 场地: (TBD) P2 加速器（新车间）
- 日期: 9月16日 14:00 - 17:00
- 人数: ～50
- 活动宣传: (TBD) https://github.com/SFD-Shanghai/SFD2017/issues/5
    - SFD official [wiki](http://wiki.softwarefreedomday.org/)
    - [活动行](http://www.huodongxing.com/)
    - others？
- 讲师: (TBD) https://github.com/SFD-Shanghai/SFD2017/issues/3
    - 主持
    - 五个主题演讲（30mins/talk）
    - 五个闪电演讲（5mins/talk）
- 饮料零食赞助: (TBD) https://github.com/SFD-Shanghai/SFD2017/issues/4
    - Wiredcraft @CCharlieLi
- 其他赞助：(TBD)
   - 红旗Linux

**Comment by CCharlieLi** [comment]
@RobberPhex @lina-not-linus @yhnmj6666  请看是否能在`活动宣传` `讲师` `赞助`认领一下相关内容，将相应的ticket assgin给自己

**Comment by dulhaver** [comment]
I may be able to help with this就是我的重要不完美。Let me know what I can do

**Comment by CCharlieLi** [comment]
@vrms Great thanks, only if you could take your friends and come this Saturday! 👍

**Comment by dulhaver** [comment]
sure. I have invited the people from #[Coderbunker](http://coderbunker.com/) already. Let's see who will be showing up

**Comment by CCharlieLi** [comment]
Closing as done.
