### ISSUE TITLE
讲师招募

### ISSUE THREAD

**Issue by CCharlieLi** [SFD-Shanghai/SFD2017#3]
### 主题演讲
- First:
    - Topic: __Firefox的新技术特性__
    - Topic Intro: 介绍关于Firefox的新特性
    - Speaker Name: 赵博通
- Second:
    - Topic: __How to contribute to the Mozilla code base__
    - Topic Intro: About how to add a new feature in Firefox. Includes webdriver-rust(Rust), geckodriver(Rust), Marionette(JavaScript & Python). About why to add this new feature, how to create these patches, using Mercurial(hg) which is a free, distributed source control management tool. Lesson Learned.
    - Speaker Name: Simon Peng
- Third:
    - Topic: __JSConf - how we make it from the beginning__
    - Topic Intro: After 6 years of JSConf China, it's time to share about what we learn from JavaScript community and event organization.
    - Speaker Name: Makara Wang
    - Speaker Intro: Senior developer at Wiredcraft
- Fourth:
    - Topic:  __My story @ Open Source__
    - Topic Intro: 讲一讲我与开源的故事，谈一谈开源的模式、说一说我的经验，畅想一下开源的未来
    - Speaker Name: Robert Lu
- Fifth:
    - Topic: __主导一个开源项目__
    - Topic Intro: 总结2年来主导GoodERP项目的经验，使大家了解开源文化和协作方式
    - Speaker Name: 王剑峰
    - Speaker Intro: 上海开阖软件有限公司总经理，资深odoo平台开发者和顾问，中国用户数最多的开源ERP项目GoodERP的发起者

### 闪电演讲
1. Charlie Maere - __OpenCV - History of Open Computer Vision Library and its impact in Artificial Intelligence__
2.
3.

**Comment by Sl0v3C** [comment]
* Topic: How to contribute to the Mozilla code base
* Topic Intro: About how to add a new feature in Firefox. Includes webdriver-rust(Rust), geckodriver(Rust),  Marionette(JavaScript & Python). About why to add this new feature, how to create these patches, using Mercurial(hg) which is a free, distributed source control management tool. Lesson Learned.
                      
* Speaker Name: Simon Peng
* Speaker Intro:

**Comment by GoodERPJeff** [comment]
Topic: 主导一个开源项目
Topic Intro: 总结2年来主导GoodERP项目的经验，使大家了解开源文化和协作方式
Speaker Name:王剑峰
Speaker Intro:上海开阖软件有限公司总经理，资深odoo平台开发者和顾问，中国用户数最多的开源ERP项目GoodERP的发起者

**Comment by CCharlieLi** [comment]
Thanks @GoodERPJeff @Sl0v3C for giving your great talks at SFD 2017! 

Please note that we'll go with above order, make sure you can arrive on time :)
You can also contact me on wechat `449217425`.

Cheers!

**Comment by cmaere** [comment]
Topic: OpenCV - History of Open Computer Vision Library and its impact in Artificial Intelligence 
Topic Intro:  OpenCV is an open source computer vision, Artificial Intelligence and machine learning software library, The library has more than 2500 optimized algorithms, which includes a comprehensive set of both classic and state-of-the-art computer vision and machine learning algorithms.Along with well-established companies like Google, Yahoo, Microsoft, Intel, IBM, Sony, Honda, Toyota that employ the library, there are many startups such as Applied Minds, VideoSurf, and Zeitera, that make extensive use of OpenCV.
Speaker Name: Charlie Maere
Speaker Intro: A Full-Stack Developer and AI Scientist

**Comment by CCharlieLi** [comment]
Closing as done. @cmaere @GoodERPJeff would be good if you can share your slides in the other issue.
