### ISSUE TITLE
活动宣传

### ISSUE THREAD

**Issue by CCharlieLi** [SFD-Shanghai/SFD2017#5]
- 活动行 http://www.huodongxing.com/event/9403757261900
- Official wiki
- ???

**Comment by oklinux** [comment]
互动把
Linux人社区（网站 、微博 、微信公众号）

**Comment by CCharlieLi** [comment]
## Software Freedom Day 2017 @ Shanghai  软件自由日上海站活动

Hi 各位，由上海JavaScript Meetup社区的Charlie、开源社社区成员“Linux人”以及上海Linux用户组的部分成员共同发起的“916，我们就要聚会”软件自由日上海站活动即将开始啦！

Hi, SFD(Software Freedom Day) 2017 is coming! WHich is hosted by Charlie from JavaScript Meetup, Linux人 community and Shanghai Linux User Group!

- 时间（Date）: 2017-09-16 14:00
- 地点（Address）: P2创客中心（愚园东路20号东海广场3号楼一楼）
P2·Hero Center, Donghai Plaza, 28 Yuyuan Road (East), Building 3, Floor 1, Jing'an District

本次活动的核心宗旨是聆听自由软件的过往，了解开源技术的魅力，关注国内各个开源技术社区的发展！我们将为众多刚刚踏入“开源殿堂”的爱好者奉献一场形式多样的大咖秀。目前活动组织群已邀请了多位大咖，并期待更多开源大咖来到我们的9.16现场就开源技术和相关知识进行分享。让我们一起欢聚一堂，喝着饮料吃着pizza，一起分享开源的乐趣。

Here we aim to talk about the history of free software, the charm of open source and the growing of Chinese open source community. Please feel free to come and give a talk if you've been part of the free software world, or you can come and let's share the drinks and pizzas and enjoy a cup of open source!

目前我们已经征集到的话题有：
For now, we have topics as :
-------------

- First:
        Topic: Firefox的新技术特性
        Topic Intro: 介绍关于Firefox的新特性
        Speaker Name: 赵博通

- Second:
        Topic: How to contribute to the Mozilla code base
        Topic Intro: About how to add a new feature in Firefox. Includes webdriver-rust(Rust), geckodriver(Rust), Marionette(JavaScript & Python). About why to add this new feature, how to create these patches, using Mercurial(hg) which is a free, distributed source control management tool. Lesson Learned.
        Speaker Name: Simon Peng

- Third:
        Topic: JSConf - how we make it from the beginning
        Topic Intro: After 6 years of JSConf China, it's time to share about what we learn from JavaScript community and event organization.
        Speaker Name: Makara Wang
        Speaker Intro: Senior developer at Wiredcraft

- Fourth:
        Topic: My story @ Open Source
        Topic Intro: 讲一讲我与开源的故事，谈一谈开源的模式、说一说我的经验，畅想一下开源的未来
        Speaker Name: Robert Lu

- Fifth:
        Topic: 主导一个开源项目
        Topic Intro: 总结2年来主导GoodERP项目的经验，使大家了解开源文化和协作方式
        Speaker Name: 王剑峰
        Speaker Intro: 上海开阖软件有限公司总经理，资深odoo平台开发者和顾问，中国用户数最多的开源ERP项目GoodERP的发起者


-------------

如果你想要在SFD活动上分享一个话题，可以在我们的github issue上提交哦～ https://github.com/SFD-Shanghai/SFD2017/issues/3.
If you wanna give a talk on the SFD event, please don't hesitate to apply at https://github.com/SFD-Shanghai/SFD2017/issues/3.

活动赞助： P2创客中心， Wiredcraft

此外，Linux人社区也希望招募学生志愿者对本次活动尝试通过微博进行视频和图文直播，有意的同学请给Llinux人社区微信公众号（linuxrenorg）留言报名。活动组织群已在Github开通了活动组织页，有意者请围观：https://github.com/SFD-Shanghai/SFD2017/issues

**Comment by CCharlieLi** [comment]
Closing as done.
